---
project:
  type: manuscript
  code-links:
  - icon: github
    text: GitHub Source
    href:  https://github.com/kai-prince-sfhea/GeneralisedErdosConjecture/blob/main/ErdosConjecture.qmd

repo-actions: false

format:
  schema-html:
    toc: true
  latex:
    toc: true
  pdf:
    lang: en-GB
    filters:
      - schema
    number-sections: true
    crossref:
      ref-hyperlink: true
    documentclass: article
    pdf-engine: lualatex
    include-in-header:
      - ../../_extensions/kai-prince-sfhea/schema/resources/TexHeader.tex
    keep-tex: true
    toc: true

terms:
  - term: Erdős
    macro: Erdos

schema:
  backlinks: false
  outlinks: false

title: "A Short Proof of a Generalised Conjecture of Erdős for Amenable Groups"

categories: [Maths, Research]

abstract: |
  We follow steps provided by the paper published by [@host2019short], 'A Short Proof of a Conjecture of Erdős Proved by Moreira, Richter and Robertson', as well as using the results provided by [@kra2022infinite], to generalise the proof of Erdős's conjecture for amenable groups. The main result that we aim to prove is: 'every positively dense subset of an amenable group contains the group sumset of $k$ infinite sets for every natural number $k$'.

draft: true
---

# Introduction

::: {#thm-GenErdosConjComb}
## [cf. @host2019short, Theorem 1]

Let $(\AmenableGroup,\GroupOperation{}{})$ be an amenable group. If $A\subseteq\AmenableGroup$ has positive density, then there exists infinite subsets $B$ and $C$ of $\AmenableGroup$ such that $\GroupOperation{B}{C}\subset A$.
:::

::: {#thm-GenErdosConjRel}
## [cf. @host2019short, Proposition 2]

There exists a set of positive density not containing any sumset of positive density and an infinite set.
:::

::: {#thm-GenNErdosConjComb}
## [cf. @kra2022infinite, Theorem 1.1]

Let $(\AmenableGroup,\GroupOperation{}{})$ be an amenable group. If $A\subseteq\AmenableGroup$ has positive density then, for every $k\in\N$, there are infinite subsets $B_1,...,B_k\subset\AmenableGroup$ such that $B_1\cdot\cdots\cdot B_k\subset A$.
:::

# Preliminaries

We will use $\N=\{1,2,3,...\}$ and $\Identity$ to denote the identity of the group $\AmenableGroup$.

## Amenable Groups and Actions

Throughout this paper, unless otherwise specified, we will let $(\AmenableGroup,\GroupOperation{}{})$ be a second countable discrete group. This also means that the Haar measure of $\AmenableGroup$ is the counting measure.

:::: {#def-FolnerSequenceDef}

{{< term ref="def-rightFolner" block=true >}}

{{< term ref="def-leftFolner" block=true >}}

{{< term ref="def-Folner" block=true >}}
::::

For simplicity of this paper, we will use the alternative and equivalent definition that a group, $\AmenableGroup$, is *amenable* (and second countable) if and only if it has a Følner sequence.

:::: {#def-TemperedSequenceDef}
## @Lindenstrauss2001PETAmenable [Definition 1.1, Proposition 1.4]

{{< term ref="def-tempered" block=true >}}

{{< term ref="prp-temperedFolner" block=true >}}
::::

:::: {#def-DensityDef}

{{< term ref="def-density" block=true >}}
::::

## Topological Dynamics of Group Actions

:::: {#def-ActionDef}
## {{< term-title ref="def-action" removeURLs=true >}}

{{< term ref="def-action" block=true >}}
::::

:::: {#def-TopologicalDynamicSystemsDef}

{{< term ref="def-topologicalDynamicalSystem" block=true >}}
::::

:::: {#def-GenericDef}

{{< term ref="def-generic" block=true >}}
::::

## Recurrence Results & Ergodic Theorems

::: {#thm-BergelsonRecurrence}
## {{< term-title ref="thm-recurrence" removeURLs=true >}}

{{< term ref="thm-recurrence" block=true >}}
:::

::: {#thm-GeneralisedPET}
## {{< term-title ref="thm-GeneralisedPET" removeURLs=true >}}

{{< term ref="thm-GeneralisedPET" block=true >}}
:::

## Erdős Cubes & Cubic Measures

## Factor Maps

## Key Dynamical Results

::: {#thm-GenErdosConjDyn}
## cf. @host2019short [Theorem 3]

Let $(X,\AmenableGroup)$ be a topological dynamical system where $\AmenableGroup$ is an amenable group, $x_0\in X$, $E$ be a clopen subset of $X$ and
$$A=\{\AmenableGroupElement\in\AmenableGroup:\GroupAction{\AmenableGroupElement}{x_0}\in E\}.$$
Let $X\times X$ be acted upon by $\AmenableGroup\times\AmenableGroup$. Let $x_1\in X$ and $\nu$ be a measure on $X\times X$ such that $(x_0,x_1)$ is generic along some Følner sequence $\Folner=(\Folner[N])_{N\in\N}$.

Assume there exists $\varepsilon>0$ and a sequence $(s_i)_{i\in\N}$ in $\AmenableGroup$ such that
$$\GroupAction{s_i}{x_0}\rightarrow x_1\text{ as }i\rightarrow\infty\text{ and }\nu(\GroupAction{s_i^{-1}}{E}\times E)\geq\varepsilon\text{ for all }i. $$
Then there exist infinite subsets $B,C\subseteq \AmenableGroup$ such that $\GroupOperation{B}{C}\subset A$.

:::

::: {#thm-GenErdosConjCube}
## cf. @kra2022infinite [Theorem 3.5]

Let $(X,\Measure,\AmenableGroup)$ be an ergodic system under the action of $\AmenableGroup$ and let $E\subset X$ be an open set with $\Measure(E)>0$.

If $a\in X$ is generic for $\Measure$ with respect to some Følner sequence $\Folner$ then, for every $k\in\N$, there exists $2$-dimensional Erd\"{o}s cube $\underline{x}=(x_{00},x_{01},x_{10},x_{11})\in X^{[[2]]}$ with $x_{00}=a$ and $x_{11}\in E$.

:::

::: {#thm-GenNErdosConjCube}
## cf. @host2019short [Theorem 4.4]

Let $(X,\Measure,\AmenableGroup)$ be an ergodic system under the action of $\AmenableGroup$ and let $E\subset X$ be an open set with $\Measure(E)>0$.

If $a\in X$ is generic for $\Measure$ with respect to some Følner sequence $\Folner$ then, for every $k\in\N$, there exists $k$-dimensional Erd\"{o}s cubes $\underline{x}\in X^{[[k]]}$ with $x_{\vec{0}}=a$ and $x_{\vec{1}}\in E$.

:::

# Proof of Theorem @thm-GenErdosConjCube

## Furstenberg's Correspondence Princple

::: {#thm-Furstenberg}
## {{< term-title ref="thm-FCP" removeURLs=true >}}

{{< term ref="thm-FCP" block=true >}}
:::

## Kronecker Factor

::: {#prp-KroneckerGeneric}
## {{< term-title ref="prp-KroneckerGeneric" removeURLs=true >}}

{{< term ref="prp-KroneckerGeneric" block=true >}}
:::

## Choosing a point $x_1$

## The joining $\nu$

## Proof Conclusion

# Proof of Corollary (ref)

# Proof of Theorem (ref)

# Discussion